### ISSUE TITLE
examples are broken in chrome/strict because of ssl

### ISSUE THREAD

**Issue by tmcw** [modestmaps/modestmaps-js#69]

**Comment by dylanpiergies** [comment]
It looks like this is a problem with GitHub itself. It's due to the JavaScript response Content-Type header being set to "text/html". Here's the error from Chrome:

Refused to execute script from 'https://raw.github.com/stamen/modestmaps-js/master/modestmaps.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 

Maybe worth raising an issue against GitHub?

**Comment by jakewan** [comment]
Another easy option would be to host the files using Github Pages.  It seems to serve .js files with a Content-Type header of 'application/x-javascript'.  Here's the same file hosted using Github Pages:

http://www.wildlemur.com/files/modestmaps/modestmaps.min.js

**Comment by drewda** [comment]
The JS file is already available from Github Pages at http://modestmaps.com/modestmaps.min.js Problem is that all the examples live in their own gists (rather than this repo), and so they'll need to be updated individually.

@tristen, would you mind updating your gists when you have time?

(Just as a side note, https://rawgithub.com/ is a nice service to use to avoid the MIME type confusion, although they prefer not being overloaded by production uses.)

**Comment by tristen** [comment]
Thanks @drewda I updated those gists. For sake of being lazy I went the `rawgithub` approach. Not sure modestmaps.com/examples will ever drive enough traffic for it to be an issue.

**Comment by drewda** [comment]
Thank you, @tristen!

@tmcw, this issue should be ready to close now.
